replicaCount: 1

image:
  repository: ghcr.io/isemene4kai/semka-informatics
  tag: "887aded8c7c00c8f983c7c651ccc04992a06ff04"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

namespace: semka-informatics

ingress:
  enabled: true
  className: traefik
  host: isemene4kai.ru
  path: /
  pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

env:
  APP_HOST: "0.0.0.0"
  APP_PORT: "8000"
  FILES_DIR: "/app/app/code_storage"
  STATIC_DIR: "/app/app/static"
  TEMPLATES_DIR: "/app/app/templates"
  VIEWS_FILE: "/app/app/views.json"

secretEnv: {}