replicaCount: 1

image:
  repository: ghcr.io/isemene4kai/semka-informatics
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: traefik
  host: isemene4kai.ru
  path: /
  pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

env:
  APP_HOST: "0.0.0.0"
  APP_PORT: "8000"
  FILES_DIR: "/srv/app/code_storage"
  STATIC_DIR: "/srv/app/static"
  TEMPLATES_DIR: "/srv/app/templates"
  VIEWS_FILE: "/srv/app/views.json"

secretEnv: {}