apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: semka-informatics
  namespace: argocd
spec:
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: semka-informatics
      images:
        - alias: semka
          imageName: ghcr.io/isemene4kai/semka-informatics:latest
          commonUpdateSettings:
            updateStrategy: digest
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
